version: "3.9"
services:
  db:
    container_name: sql1
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "14333:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - sql1data:/var/opt/mssql
volumes:
  sql1data: